// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Body_Fatigue_Predict_Rating_ML
{
    public partial class OTRMLModel
    {
        /// <summary>
        /// model input class for OTRMLModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"AverageLyingBPM")]
            public float AverageLyingBPM { get; set; }

            [ColumnName(@"MaxLyingBPM")]
            public float MaxLyingBPM { get; set; }

            [ColumnName(@"MinLyingBPM")]
            public float MinLyingBPM { get; set; }

            [ColumnName(@"AverageLyingIBI")]
            public float AverageLyingIBI { get; set; }

            [ColumnName(@"MaxLyingIBI")]
            public float MaxLyingIBI { get; set; }

            [ColumnName(@"MinLyingIBI")]
            public float MinLyingIBI { get; set; }

            [ColumnName(@"AverageStandingBPM")]
            public float AverageStandingBPM { get; set; }

            [ColumnName(@"MaxStandingBPM")]
            public float MaxStandingBPM { get; set; }

            [ColumnName(@"MinStandingBPM")]
            public float MinStandingBPM { get; set; }

            [ColumnName(@"AverageStandingIBI")]
            public float AverageStandingIBI { get; set; }

            [ColumnName(@"MaxStandingIBI")]
            public float MaxStandingIBI { get; set; }

            [ColumnName(@"MinStandingIBI")]
            public float MinStandingIBI { get; set; }

            [ColumnName(@"DiffPositionBpm")]
            public float DiffPositionBpm { get; set; }

            [ColumnName(@"DiffPositionIbi")]
            public float DiffPositionIbi { get; set; }

            [ColumnName(@"Rating")]
            public float Rating { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for OTRMLModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"AverageLyingBPM")]
            public float AverageLyingBPM { get; set; }

            [ColumnName(@"MaxLyingBPM")]
            public float MaxLyingBPM { get; set; }

            [ColumnName(@"MinLyingBPM")]
            public float MinLyingBPM { get; set; }

            [ColumnName(@"AverageLyingIBI")]
            public float AverageLyingIBI { get; set; }

            [ColumnName(@"MaxLyingIBI")]
            public float MaxLyingIBI { get; set; }

            [ColumnName(@"MinLyingIBI")]
            public float MinLyingIBI { get; set; }

            [ColumnName(@"AverageStandingBPM")]
            public float AverageStandingBPM { get; set; }

            [ColumnName(@"MaxStandingBPM")]
            public float MaxStandingBPM { get; set; }

            [ColumnName(@"MinStandingBPM")]
            public float MinStandingBPM { get; set; }

            [ColumnName(@"AverageStandingIBI")]
            public float AverageStandingIBI { get; set; }

            [ColumnName(@"MaxStandingIBI")]
            public float MaxStandingIBI { get; set; }

            [ColumnName(@"MinStandingIBI")]
            public float MinStandingIBI { get; set; }

            [ColumnName(@"DiffPositionBpm")]
            public float DiffPositionBpm { get; set; }

            [ColumnName(@"DiffPositionIbi")]
            public float DiffPositionIbi { get; set; }

            [ColumnName(@"Rating")]
            public uint Rating { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public float PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("OTRMLModel.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
